test-job:
  script:
    - echo "This is my first job"
    - date

build-job:
  image: node
  script:
    - echo "Begin testing"
    - npm install
    - npm run build
  artifacts:
    paths:
      - "build/"

