stages:
  - build
  - deploy

test-job:
  stage: build
  script:
    - echo "This is my first job"
    - date

build-job:
  stage: build
  image: node
  script:
    - echo "Begin testing"
    - npm install
    - npm run build
  artifacts:
    paths:
      - "build/"


pages:
  stage: deploy
  script:
    mv build/ public/
  artifacts:
    paths:
      - "public/"